## =========================================================================================================================================================
##
## R code to generate Figure 5 and S4 in Appendix 2 for manuscript titled "The Eco-Epidemiological Dynamics of Evolutionary Rescue in a Host Metapopulation"

## =========================================================================================================================================================

library(ggplot2)
library(reshape)
library(here)

## set the current directory as default to save all the following results
set_here()
##The csv. files are generated by the Matlab code named as "Figure_5_with_S4.m"
cyc_RT_matr<-read.csv("SIRmodel_RT_cycles_avepop_aveInfect_Mig_vs_Growth.csv",header=TRUE)
cyc_WT_matr<-read.csv("SIRmodel_WT_cycles_avepop_aveInfect_Mig_vs_Growth.csv",header=TRUE)

#assign matrix to each patch
cyc_RT_patch1<-cyc_RT_matr[,1:3]
cyc_RT_patch15<-cyc_RT_matr[,c(1,2,4)]
cyc_RT_patch30<-cyc_RT_matr[,c(1,2,5)]
cyc_RT_patch40<-cyc_RT_matr[,c(1,2,6)]

cyc_WT_patch1<-cyc_WT_matr[,1:3]
cyc_WT_patch15<-cyc_WT_matr[,c(1,2,4)]
cyc_WT_patch30<-cyc_WT_matr[,c(1,2,5)]
cyc_WT_patch40<-cyc_WT_matr[,c(1,2,6)]

#average_population (S+I+R)
avep_RT_patch1<-cyc_RT_matr[,c(1,2,7)]
avep_RT_patch15<-cyc_RT_matr[,c(1,2,8)]
avep_RT_patch30<-cyc_RT_matr[,c(1,2,9)]
avep_RT_patch40<-cyc_RT_matr[,c(1,2,10)]

avep_WT_patch1<-cyc_WT_matr[,c(1,2,7)]
avep_WT_patch15<-cyc_WT_matr[,c(1,2,8)]
avep_WT_patch30<-cyc_WT_matr[,c(1,2,9)]
avep_WT_patch40<-cyc_WT_matr[,c(1,2,10)]

# #dampslope 'NA':not enough cycles; 
damps_RT_patch1<-cyc_RT_matr[,c(1,2,11)]
damps_RT_patch15<-cyc_RT_matr[,c(1,2,12)]
damps_RT_patch30<-cyc_RT_matr[,c(1,2,13)]
damps_RT_patch40<-cyc_RT_matr[,c(1,2,14)]

damps_WT_patch1<-cyc_WT_matr[,c(1,2,11)]
damps_WT_patch15<-cyc_WT_matr[,c(1,2,12)]
damps_WT_patch30<-cyc_WT_matr[,c(1,2,13)]
damps_WT_patch40<-cyc_WT_matr[,c(1,2,14)]


#heatmap for each patch

##define axises
x_axis=seq(0.0000005,0.000037,0.0000013) #x_axis is Mig_rate

y_axis=seq(1.01,2,0.035) #y_axis is Growth_rate

colnames(cyc_WT_patch30)


theme_set(theme_bw(20))

##X1, X1.1 and X0.2 are the colnames of cyc_WT_patch30

tiff("Figure_5.tiff", width=10,height=10, units='in',res=600)


p1 <- ggplot(cyc_WT_patch30, aes(x_axis[X1],y_axis[X1.1])) + geom_tile(aes(fill = X0.2))+ guides(fill = guide_colorbar(title="Cycle Num"))+geom_text(aes(label = round(Patch.30,4)),size=4)+theme(legend.title = element_text(size=10))


p1+xlab("Mig_rate")+ylab("Growth_Ratio")+ scale_fill_gradient2(low = 'steelblue', mid='white',high = 'red' ,
                                                              
                                                              midpoint=median(cyc_WT_patch30[,3]), space = "rgb", na.value = "grey50", guide = 
                                                                
                                                                "colourbar")+scale_x_continuous(expand=c(0,0)) + scale_y_continuous(expand=c(0, 0))



dev.off()  



colnames(avep_WT_patch30)


tiff("Figure_S4a.tiff", width=10,height=10, units='in',res=600)

##X1, X1.1 and X2819.2 are the column names of avep_WT_patch30

p1 <- ggplot(avep_WT_patch30, aes(x_axis[X1],y_axis[X1.1])) + geom_tile(aes(fill = X2819.2/K))+ guides(fill = guide_colorbar(title="Ave pop"))


p1+xlab("Mig_Rate")+ylab("Growth_Ratio")+ scale_fill_gradient2(low = 'steelblue', mid='white',high = 'red' ,
                                                                  
                                                                  midpoint=median(avep_WT_patch30[,3]/K), space = "rgb", na.value = "grey50", guide = 
                                                                    
                                                                    "colourbar")+scale_x_continuous(expand=c(0,0)) + scale_y_continuous(expand=c(0, 0))


dev.off()  



tiff("Figure_S4b.tiff", width=10,height=10, units='in',res=600)



p1 <- ggplot(avep_RT_patch30, aes(x_axis[X1],y_axis[X1.1])) + geom_tile(aes(fill = X2819.2/K))+ guides(fill = guide_colorbar(title="Ave pop"))


p1+xlab("Mig_Rate")+ylab("Growth_Ratio")+ scale_fill_gradient2(low = 'steelblue', mid='white',high = 'red' ,
                                                                  
                                                                  midpoint=median(avep_RT_patch30[,3]/K), space = "rgb", na.value = "grey50", guide = 
                                                                    
                                                                    "colourbar")+scale_x_continuous(expand=c(0,0)) + scale_y_continuous(expand=c(0, 0))



dev.off()  



